#!/usr/bin/env bash

scaffold:init () {
  export service="$1"
  export serviceDir="$2"

  if [[ -d ${serviceDir} ]]; then
    echo "${service} already exists at $serviceDir"
    exit 1
  fi

  mkdir -p "$serviceDir"
  cd "$serviceDir" || exit
}

scaffold:readme () {
  [[ -f README.md ]] || cat <<EOF > README.md
# ${service}
EOF
  echo ' - Created a README.md'
}

scaffold:directories () {
  [[ -d ./src ]] || mkdir "./src"
  [[ -d ./test ]] || mkdir "./test"
  echo ' - Created default directories'
}

scaffold:dotfiles () {
  [[ -f .gitignore ]] || touch .gitignore
  [[ -f .editorconfig ]] || touch .editorconfig
  echo ' - Created default dotfiles'
}

scaffold:taskrunner () {
  [[ -f ./koshu.sh ]] || curl -s https://raw.githubusercontent.com/kristofferahl/koshu-shell/master/src/koshu.sh > ./koshu.sh
  chmod +x ./koshu.sh
  ./koshu.sh init > /dev/null
  echo ' - Added koshu and default koshufile'
}

scaffold:git:local () {
  git init > /dev/null
  git add .
  git commit -am "Created service $service" > /dev/null
  echo ' - Initialized local git repository'
}

scaffold:git:github () {
  ask_for useGithub 'Setup Github project' 'yes'

  if [[ "$useGithub" != "yes" ]]; then
    echo 'Skipping Github setup...'
  else
    ask_for githubOrganization 'Github organization'
    ask_for githubToken 'Github API token'

    response=$(curl https://api.github.com/orgs/${githubOrganization}/repos \
      -H "Authorization: token ${githubToken}" \
      -o /dev/null \
      --write-out "%{http_code}\n" \
      --silent \
      -d "{
            \"name\": \"${service}\",
            \"private\": true
          }")

    if [[ "$response" == "201" ]]; then
      echo " - Github project created (https://github.com/${githubOrganization:?}/${service}/)"

      git remote add origin git@github.com:${githubOrganization}/${service}.git
      echo " - Added remote 'origin' to git repository (git@github.com:${githubOrganization}/${service}.git)"
    else
      echo " - Failed to create Github project (HTTP $response)"
      exit 1
    fi
  fi
}

scaffold:git () {
  scaffold:git:local
  scaffold:git:github
}

ask_for () {
  local var="$1"
  local prompt="$2"
  local default="$3"

  echo
  echo -n "${prompt} (${default}) : "
  read answer
  if [[ -z $answer ]]; then
    printf -v "${var}" '%s' "${default}"
  else
    printf -v "${var}" '%s' "${answer}"
  fi

}

main () {
  local service="${1:?'A service name must be provided'}"

  echo "Creating service '$service'..."
  echo 'Press enter to accept default value when prompted.'

  ask_for serviceDir "Root directory" "${PWD}/$service/"

  scaffold:init "$service" "$serviceDir"
  scaffold:readme
  scaffold:directories
  scaffold:dotfiles
  scaffold:taskrunner
  scaffold:git
}

main "$1"
